apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-connect.fullname" . }}-connectors
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
data:
  debezium-source.json: |
{{ .Values.connectors.debeziumSourceJson | indent 4 }}

  dynamodb-sink.json: |
{{ .Values.connectors.dynamodbSinkJson | indent 4 }}

  dynamodb-tables.json: |
{{ .Values.connectors.dynamodbTablesJson | indent 4 }}

  init_connectors.sh: |
{{ .Values.connectors.initScript | indent 4 }}