apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka-connect.fullname" . }}-init-job
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-connectors
          image: curlimages/curl:latest
          env:
            - name: CONNECT_URL
              value: "http://{{ include "kafka-connect.fullname" . }}:{{ .Values.service.port }}/connectors"
          volumeMounts:
            - name: connector-configs
              mountPath: /config
          command: ["/bin/sh", "/config/init_connectors.sh"]
      volumes:
        - name: connector-configs
          configMap:
            name: {{ include "kafka-connect.fullname" . }}-connectors