services:
  api:
    build: backend
    container_name: backend
    environment:
      # - APP_ENV=production

      # --- Feature Flags ---
      - FEATURES__POSTGRES=True
      - FEATURES__DYNAMODB=True
      - FEATURES__CENTRIFUGO=True
      - FEATURES__CACHE_REDIS=True
      - FEATURES__EVENT_HANDLERS=True
      - FEATURES__KAFKA=True

      # --- Connection Strings ---
      - DYNAMODB__URL=http://dynamodb:8000
      - REDIS__URL=redis://redis:6379/1
      - POSTGRES__URL=postgresql+asyncpg://harmony:harmony@postgres:5432/harmony
      - CENT__URL=http://centrifugo:8000/api
      - KAFKA__BOOTSTRAP_SERVERS=kafka:9092

      - CENT__API_KEY=your-secure-backend-api-key

      # --- AWS Config ---
      - AWS__ACCESS_KEY_ID=test
      - AWS__SECRET_ACCESS_KEY=test
      - AWS__DEFAULT_REGION=us-east-1
      - AWS__REGION=us-east-1
    depends_on:
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_started
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  # frontend:
  #   build: 
  #     context: frontend
  #     args:
  #       - NEXT_PUBLIC_CENTRIFUGE_URL=ws://localhost:8010/connection/websocket
  #   environment:
  #     - INTERNAL_API_ENDPOINT=http://api:8000
  #   depends_on:
  #     api:
  #       condition: service_started
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=harmony
      - POSTGRES_PASSWORD=harmony
      - POSTGRES_DB=harmony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harmony -d harmony"]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -cors *"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
       interval: 5s
       timeout: 5s
       retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  centrifugo:
    image: centrifugo/centrifugo:v6
    container_name: centrifugo
    volumes:
      - ./infra/config/centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8010:8000"
    depends_on:
      redis:
        condition: service_healthy

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-connect:
    build:
      context: infra/docker/dynamodb-sink
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      dynamodb:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 6

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=harmony-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  init:
    build: backend
    container_name: init
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1

      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - TABLE_FILE=infra/config/dynamodb-tables.json

      - CONNECT_URL=http://kafka-connect:8083/connectors
      - CONFIG_FILE=infra/config/dynamodb-sink.json
    depends_on:
      dynamodb:
        condition: service_started
      postgres:
        condition: service_healthy
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./infra/:/app/infra/:ro
    command: python infra/local/init.py

volumes:
  postgres_data:
  dynamodb_data:
  redis_data:
  kafka_data: