services:
  api:
    build: backend
    container_name: backend
    environment:
      # - APP_ENV=production

      # --- Feature Flags ---
      - FEATURES__POSTGRES=True
      - FEATURES__DYNAMODB=True
      - FEATURES__CENTRIFUGO=True
      - FEATURES__CACHE_REDIS=True
      - FEATURES__EVENT_HANDLERS=True

      # --- Connection Strings ---
      - DYNAMODB__URL=http://dynamodb:8000
      - REDIS__URL=redis://redis:6379/1
      - POSTGRES__URL=postgresql+asyncpg://harmony:harmony@postgres:5432/harmony
      - CENT__URL=http://centrifugo:8000/api

      - CENT__API_KEY=your-secure-backend-api-key

      # --- AWS Config ---
      - AWS__ACCESS_KEY_ID=test
      - AWS__SECRET_ACCESS_KEY=test
      - AWS__DEFAULT_REGION=us-east-1
      - AWS__REGION=us-east-1
    depends_on:
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_started
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  # frontend:
  #   build: 
  #     context: frontend
  #   depends_on:
  #     api:
  #       condition: service_started
  #   ports:
  #     - "3000:3000"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=harmony
      - POSTGRES_PASSWORD=harmony
      - POSTGRES_DB=harmony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harmony -d harmony"]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -cors *"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
       interval: 5s
       timeout: 5s
       retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    volumes:
      - ./infra/config/centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json --log_level debug
    ports:
      - "8001:8000"
    depends_on:
      redis:
        condition: service_healthy

  init:
    build: backend
    container_name: init
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000

      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
    depends_on:
      - dynamodb
      - postgres
    volumes:
      - ./infra/:/app/infra/:ro
    command: python infra/local/init_db.py --table-file infra/config/tables.json

volumes:
  postgres_data:
    driver: local
  dynamodb_data:
    driver: local
  redis_data:
    driver: local