version: '3'  

tasks:
  build:
    desc: "Build the docker compose environment"
    dir: backend
    cmds:
      - docker-compose build

  run-local:
    desc: "Run local docker compose in a simple development environment"
    dir: backend
    cmds:
      - docker-compose up

  run-local-sim:
    desc: "Run local docker compose environment mirroring production setup"
    dir: backend
    cmds:
      - docker-compose -f infra/local/local-simulation.yaml up --build

  test:
    desc: "Run tests against the server"
    dir: backend/src/simple_discord/tests
    env:
      API_ENDPOINT: http://localhost:8000
      API_PATH: /api/v1
    cmds:
      - pytest -m integration

  test-stress:
    desc: "Run stress tests against the server"
    dir: backend/src/simple_discord/tests
    env:
      API_ENDPOINT: http://localhost:8000
      API_PATH: /api/v1
    cmds:
      - pytest -m stress -s -v
  
