version: '3'  

vars:
  CONDA_ENV: harmony
  PYTHON_CMD: "conda run --no-capture-output -n {{.CONDA_ENV}} python"
  PYTEST_CMD: "conda run --no-capture-output -n {{.CONDA_ENV}} pytest"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  # --------------------------------------------------------------------------
  # 1. SETUP & CONFIGURATION
  # --------------------------------------------------------------------------

  setup:
    desc: "ðŸš€ SETUP: the development environment"
    summary: |
      1. Creates the 'harmony' Conda environment.
      2. Installs the backend in editable mode.
      3. Installs frontend Node modules.
    cmds:
      - task: setup:conda
      - task: setup:backend
      - task: setup:frontend
    status:
      - test -d frontend/node_modules
      - conda env list | grep {{.CONDA_ENV}}

  setup:conda:
    internal: false
    desc: "Create Conda environment"
    cmds:
      - conda env create -f environment.yaml || echo "Env likely exists, updating..."
      - conda env update --name {{.CONDA_ENV}} --file environment.yaml --prune
  
  setup:backend:
    internal: true
    desc: "Install Backend Dependencies"
    cmds:
      - "{{.PYTHON_CMD}} -m pip install -e backend"

  setup:frontend:
    internal: true
    desc: "Install Frontend Dependencies"
    dir: frontend
    cmds:
      - npm install

  # --------------------------------------------------------------------------
  # 2. RUNNING THE APP
  # --------------------------------------------------------------------------

  run:dev:
    desc: "â–¶ï¸  START DEV: Runs the local dev environment"
    cmds:
      - docker compose up --build

  run:sim:
    desc: "â–¶ï¸  START SIMULATION: Runs the Prod-mirror environment"
    cmds:
      - docker compose -f docker-compose.yaml -f infra/local/docker-compose.yaml up --build

  clean:
    desc: "ðŸ›‘ STOP: Stops all containers and removes volumes"
    cmds:
      - docker compose down --volumes --remove-orphans
        
  build:
    desc: "ðŸš€ BUILD: the docker compose environment"
    cmds:
      - docker compose build

  # --------------------------------------------------------------------------
  # 3. TESTING
  # --------------------------------------------------------------------------

  test:integration:
    desc: "ðŸ§ª Run integration tests"
    dir: backend/src/harmony/tests
    env:
      API_ENDPOINT: http://localhost:8000
    cmds:
      - "{{.PYTEST_CMD}} -m integration"

  test:stress:
    desc: "ðŸ§ª Run stress tests"
    dir: backend/src/harmony/tests
    env:
      API_ENDPOINT: http://localhost:8000
    cmds:
      - "{{.PYTEST_CMD}} -m stress -s -v"

  data:generate:
    desc: "ðŸŽ² GENERATE: dummy data for the DB"
    dir: backend/src/harmony/tests/tools
    cmds:
      - "{{.PYTEST_CMD}} generate.py -s"

  data:clean:
    desc: "ðŸŽ² CLEAN: up generated test data from the database"
    dir: backend/src/harmony/tests/tools
    cmds:
      - rm -f generated_data.json

  # --------------------------------------------------------------------------
  # 4. CODE GENERATION & SYNC
  # --------------------------------------------------------------------------

  schema:sync:
    desc: "ðŸ”„ SYNC: Updates Frontend SDK based on Backend Code"
    summary: |
      Use this when you change the FastAPI Pydantic models.
      1. Extracts OpenAPI JSON from Backend.
      2. Generates TypeScript clients using Orval.
    cmds:
      - "{{.PYTHON_CMD}} backend/specs/extract_openapi.py > frontend/openapi.json"
      - cd frontend && npx orval

  env:freeze:
    desc: "ðŸ”„ FREEZE: Update environment.yaml from current setup"
    cmds:
      - 'conda run -n {{.CONDA_ENV}} conda env export --no-builds | grep -v -e "prefix: " -e "harmony-chat-api" > environment.yaml'

  env:compile:
    desc: "ðŸ”„ COMPILE: generate requirements.txt from pyproject.toml"
    dir: backend
    cmds:
      - pip-compile pyproject.toml --output-file requirements.txt