/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CentrifugoSubscribeRequest {
  client: string;
  transport: string;
  protocol: string;
  user: string;
  channel: string;
}
