/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CentrifugoConnectRequest {
  client: string;
  transport: string;
  protocol: string;
  encoding: string;
}
