/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserMetaData } from "./userMetaData";

export interface ChatMessageResponse {
  chat_id: string;
  ulid: string;
  client_uuid?: string | null;
  timestamp: string;
  user_id: string;
  content: string;
  author_metadata?: UserMetaData | null;
}
