/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessageResponse } from "./chatMessageResponse";

export interface ChatHistoryResponse {
  messages: ChatMessageResponse[];
  next_cursor?: string | null;
}
