/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMetaData } from "./chatMetaData";

export interface ChatResponse {
  chat_id: string;
  created_at: string;
  meta: ChatMetaData;
}
