/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatCreateRequest {
  title?: string | null;
  description?: string | null;
  /** @maxItems 10 */
  user_id_list: string[];
}
