/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetUserDetailsByEmailApiV1UsersLookupGetParams = {
  email: string;
  /**
   * @maximum 10
   * @exclusiveMinimum 0
   */
  limit?: number;
};
