/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserChatItem } from "./userChatItem";

export interface UserChatsResponse {
  chats: UserChatItem[];
}
