/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserMetaData } from "./userMetaData";

export interface UserResponse {
  user_id: string;
  email: string;
  tombstone: boolean;
  meta: UserMetaData;
}
