apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "init-job.fullname" . }}-config
  labels:
    {{- include "init-job.labels" . | nindent 4 }}
data:
  dynamodb-tables.json: |-
{{- toPrettyJson .Values.config.dynamodbTables | nindent 4 }}