apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "init-job.fullname" . }}-dynamodb
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-dynamodb
          image: {{ .Values.image.dynamodbInit }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DYNAMODB_ENDPOINT
              value: {{ .Values.dynamodb.endpoint | quote }}
            - name: AWS_REGION
              value: {{ .Values.dynamodb.region | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-auth-secret
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-auth-secret
                  key: secret_access_key
            - name: TABLE_FILE
              value: "/config/dynamodb-tables.json"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "init-job.fullname" . }}-config