secrets:
    app:
        secret_key: ENC[AES256_GCM,data:BSHEkUncqiCAVDcK1e7ZAzeocDANzRPgRts8+kWFtQNf50DfAgAaxF/UP93LuqzX1BQo+G3OwhV7nBPRIEUWPA==,iv:ycgivbTPdR9qg1gqArYaMn/St70ixh5rT2Gz7e4j8mc=,tag:JJ85tRTzmiN2P+6WZmgX5g==,type:str]
    postgres:
        password: ENC[AES256_GCM,data:Vx6oxSyZrX+HVmfzCqflfXt3pxXVQ4B2,iv:gvriDtHz2QDkWvCUHRCc0+jN8r4+135VwB7QydG1LzM=,tag:hqmlzA53Vu/nxjY/tlNTTw==,type:str]
    aws:
        access_key_id: ENC[AES256_GCM,data:fiMbaYLiGC6nwqTuDsWoR3bN3uQ=,iv:ov1S9JhAgCGNovsfNnNqgd+93mo56lDIaXHMbZiLD60=,tag:DpivnFcQzm5h4pO5xGas4g==,type:str]
        secret_access_key: ENC[AES256_GCM,data:lQ+GyskzOJrAbbSFruZYhmHogJmFu/DfkA9I1kEElqXmvjHKagOV+w==,iv:x/grT/HyX7XwR4GEObkcgMn0Bi3ovv20kCd7eZ6MtIw=,tag:matZ8T2pWzm5KTjMz8E0iw==,type:str]
    s3:
        access_key: ENC[AES256_GCM,data:7O/hnJc8RcsJ2F1/P3IH2aEWyEA=,iv:wZg7/1bt3gt7GP9yM7m0nRPixYOS/8vEuYqDSnK9a1E=,tag:YVu6WPVNcHnCs6UzvdEO9Q==,type:str]
        secret_key: ENC[AES256_GCM,data:9OOQB2YsJyiJr9eKtFxzoD03NzUIdmUdUaRJc4rLdNBzs10c+jl0Gg==,iv:vmLmsnUR8v0mpkOtAPhuwgRMv2ukcu6ztHhuhE9qW9s=,tag:pe3w+to+eozV01WrLY+P7g==,type:str]
    centrifugo:
        api_key: ENC[AES256_GCM,data:TbXdEoSLQDqICGv6CbRzI503g2O4I5c17V/crj5IAiQ=,iv:ghYNlFMHsMKQv5nWCbNX7lui2H5qcjRClWAC7uB9iKA=,tag:chSMiBo+THEKi23zMOBLtA==,type:str]
        admin_password: ENC[AES256_GCM,data:8g83b5xfEWV5zi787x1bwg==,iv:lv8ch/dDGfl0mO4IcFK2YZvWnXXITHB3GxYN5KOrhME=,tag:MPXNAKZLUzASxuFuD07TMA==,type:str]
        admin_secret: ENC[AES256_GCM,data:ABtFGfB1JNJcXXcNoDvbdLIQHo4u1zvrUpme7jawhSI=,iv:vGhEyHE6bZo50oK0zRlBQ9tDjJJ/I9aiAC5uTzHeqjY=,tag:wSoopVNeae0+9ihtPko1qw==,type:str]
    spacelift:
        api_key_endpoint: ENC[AES256_GCM,data:T4JS3cutNg4/6ZJ7+sWZCWECpvjk2dMmyTwPqfhyCk+nqjWM95s9hkg=,iv:FKroF2KBv8G/9IpMI1H8OQkpqcvY7JS0yiuOOlETzUM=,tag:q77ogXV5EaSp9VX5F5vDrQ==,type:str]
        api_key_id: ENC[AES256_GCM,data:KAgUl/Y8k/eR7oFM3pfTAdQ+fzlQWv9Yp4U=,iv:/f5vO5uYr9Uc+nwAVxbAJkt0LbBcTGAo4LKU4ZyDgu0=,tag:SC4+D9kTfP6ooszs8/dvJQ==,type:str]
        api_key_secret: ENC[AES256_GCM,data:dSJpzyfEADKxqhvC5O9S5BfPSLWJU+6XsXvqplFU3q1vbv6CF/axxCydyv9/FQ+B/YDLv2W24PPNCtQP9ZA8MA==,iv:rW+I53xpdnWeyfR0Wi7QxQVcdOnxpG/pBlyxqvNLD8U=,tag:v0JSH6Kjel0TSAgByt5hwQ==,type:str]
sops:
    age:
        - recipient: age14v7sn2jseh9g29uchreyn5gxlm0fy3qasdwvghwrq6ae4qsdv9hsk0p3yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVDFvUUhrc2wwUm96dkJ4
            Rm40ZHl5SDVVNEY1QzV4RWhEVUwyL0xKZ3hjCjY0d2pzcldyMUtCakZCYVM2b2da
            RnhlSGNyUDArMlVsUUxwd0h1R2xtNTAKLS0tIGNTOG1QQXhvZXF2UDdGRnVpM2hx
            eHIzTTB0M3NFVTlmNVd4WkFuc0tHYW8KQJyFOUZiBNElryABalJZCmQMAEHpEuCN
            6l1QWosdYVJt4UpqxA41iDzlXoEgJB4JcpyfiFNb6th0iYpPa9HNWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T06:11:27Z"
    mac: ENC[AES256_GCM,data:o/mfPjzKyegQLtUWBMCb2uI95NKCAOp1pwDSQGlmo2wvmuS7CfAdvlEq/OeIrbrT0Bg6EsuiqLsr7S1RrMYmTz2E6GUG+MIWhHz7svZ071kmuqEzOd7H2024StaMPWcmtGobt3CQBTVYFoQlsMeeBc2+ywTibRV+UG08Eslbpt0=,iv:YQPMjO0sEtTw/HTDMtQRNV+G6c+nvPfjNCkjPbHwu9Q=,tag:hVLwdR9JDkq05GplQErlXA==,type:str]
    encrypted_regex: ^(secrets)$
    version: 3.12.2
