secrets:
    app:
        secret_key: ENC[AES256_GCM,data:wbQVCz9TYEC9T1P1mkfFtvarPOXl6Swpk/OEH2qeG5Ll95sNE4Y6I0R2EEvZK7mvDRyZ9buA/SYRyOazt9XPdw==,iv:RfbWr7DMaAkuQ3zWpVrBif2Jl9FXvs2axSmCjCMyNdY=,tag:YEAqj3HL98hJJ0loqIs4PA==,type:str]
    postgres:
        password: ENC[AES256_GCM,data:FkI6MkdiP1XZ6TYNOQ6FKAVmG8qZ3auy,iv:jI2ncaxF/K8PzvA/Eeu2wrSngTo5w7Cw4kQPurpXpTk=,tag:8njdR+nKBJdSuI29TxqPWQ==,type:str]
    aws:
        access_key_id: ENC[AES256_GCM,data:Ec3lc1XSDErzDnCngRAipIpDb8g=,iv:7vPRVbh3yA5F2a1IvCBxMPuOlUOfkSyHiD/wp1iNMlE=,tag:HThyzkeJffFgxp7A1/Fmpg==,type:str]
        secret_access_key: ENC[AES256_GCM,data:8ssr/jXLZQlkqwQ6J/ivtThj1wjJczXHdw623lKU7ynLDPYocgbyJw==,iv:4nAZB5tdkSn2Bym/dtluDbtNiiLgBiR1N3YnEuCIyZU=,tag:Ciituv9m+hrOkTdfVXDY8Q==,type:str]
    s3:
        access_key: ENC[AES256_GCM,data:Z1KlIihG+SgEkdbsrFsdIPFef3w=,iv:kmQUJGw13uZunuRj7H+Pc6SD+fbC92+UcYazCeE0xwg=,tag:281xU/nwg6WGEg37lt8lXA==,type:str]
        secret_key: ENC[AES256_GCM,data:GFpAk89a7bRrxsrcgeHGW8KjP0JORllvqQkhCrXWU3kYuRIqELB64A==,iv:zGG1Dqu5st786vLab4p+/5nPPDRL8I6cXqPA101Zp+s=,tag:oXmqilYbgWvPjJSWh7tBig==,type:str]
    centrifugo:
        api_key: ENC[AES256_GCM,data:PBPlyRXqzfeztu+bkkfCyojG4F8j41QZHs+V+JdHLAA=,iv:nvL7fAqdDTpJLVrcxzSoncL3AwFcWBPYFk2TY/8nhq4=,tag:BD6GnJRW8aWio079YP0HRQ==,type:str]
        admin_password: ENC[AES256_GCM,data:boex8aVvY3Rtc9YgsS8rug==,iv:+pSsbT90ui1Xdx61cS/loTReEquTjSs/TJHJTQnXWSk=,tag:daGYxyPT7IFD92GJqgR7fA==,type:str]
        admin_secret: ENC[AES256_GCM,data:tIPChoF2g4iTqU1uxGdI4ZvUldVQzwUFlOToy8OO9G8=,iv:DAdzAMy9mKZ5Ko94uCMFdYjgsZ9j5QxVK5Wj60Xhr2w=,tag:Px3LmSl9j8s/V1PiL6BWlQ==,type:str]
sops:
    age:
        - recipient: age1kvfwns08ldyhexhgx0vtl4fz6l4j795sf7xh5228353tn50an9tqrx7uzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOFNveHFNVXE2YUQ3Sy9h
            K1o5S1Y2Yk1HdE8vcjExci9oU1Mrem1ZTFhVCmQxaUs3NEVxMXk5UVhjUkJQdlFX
            cHJNMUpndWxoaWZwNEpza1E5OFRHRmsKLS0tIFJWOEhOZ1hVLzZxYytvbDVLb05j
            VjJ5c1RQSkN4MWRBcXlUVTBYRzNCNFUKht8FfyV/m0zM4/t8fPnGw5EeFq6zEahN
            JU/E4JYqtOzIjnpGYtWeW2WDLAV/P0nL0yHlEVHevg5AvH/LZtH1Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T02:26:18Z"
    mac: ENC[AES256_GCM,data:AcJiwTGrBhiB+FVxp0QbbheFWW7gmZothOcKJotro1BzxC0o2Kj9RvLOD40YiwfpQaLVqN5JHRJMKJY16fLJMLB8rACRbMLCb0ucz3wR+DankkbAYMt4C5liP/8ghKIG/+VDcH7lWgbRIyNbjZN7xp5nNDAnmTKcUdNpqTIpbnc=,iv:WxYGeZ1Fu3qPZJi7KAginZi/Ap2LeHE69tOpGnc01h0=,tag:el7H+3COEBwDbJtKK4YN3A==,type:str]
    encrypted_regex: ^(secrets)$
    version: 3.12.2
