replicaCount: 1

image:
  repository: conduit.docker.scarf.sh/conduitio/conduit
  tag: latest
  pullPolicy: IfNotPresent

postgresSecret:
  name: postgres-auth-secret
  key: postgres_password

pipeline:
  filename: postgres-cdc.yaml
  mountDir: /app/pipelines

pipelineConfig: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podAnnotations: {}