replicaCount: 1

image:
  repository: harmony-backend
  tag: local
  pullPolicy: Never

command: []
args: []

env: {}

service:
  enabled: false
  type: ClusterIP
  port: 8000
  nodePort: null

livenessProbe: {}
readinessProbe: {}

resources: {}