replicaCount: 1

image:
  repository: harmony-backend
  tag: local
  pullPolicy: Never

# command = [] for api server, command = [python -m harmony.consumer.main] for consumer
command: []
args: []

# Imported through template rendering
envFileContent: ""

# service.enabled = true for api server, service.enabled = false for consumer
service:
  enabled: false
  type: ClusterIP
  port: 8000
  nodePort: null

livenessProbe: {}
readinessProbe: {}

resources: {}