environments:
  local:
    values:
      - config.yaml

helmDefaults:
  createNamespace: true
  cleanupOnFail: false
  wait: true
  timeout: 600

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: minio
    url: https://charts.min.io/
  - name: redpanda
    url: https://charts.redpanda.com
  - name: centrifugal
    url: https://centrifugal.github.io/helm-charts
  - name: kafbat
    url: https://kafbat.github.io/helm-charts

---

releases:
  - name: minio
    namespace: harmony
    chart: minio/minio
    values:
      - values/minio.yaml.gotmpl
    wait: true

  - name: automq
    namespace: harmony
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 31.5.0
    values:
      - values/automq.yaml.gotmpl
    needs:
      - harmony/minio
    wait: true

  - name: postgresql
    namespace: harmony
    chart: bitnami/postgresql
    values:
      - values/postgres.yaml.gotmpl
    wait: true

  - name: redis
    namespace: harmony
    chart: bitnami/redis
    values:
      - values/redis.yaml.gotmpl
    wait: true

  - name: dynamodb-local
    namespace: harmony
    chart: ../../charts/dynamodb-local
    values:
      - values/dynamodb-local.yaml.gotmpl
    wait: true

  - name: consumer
    namespace: harmony
    chart: ../../charts/harmony
    values:
      - values/consumer.yaml.gotmpl
    set:
      - name: envFileContent
        file: env/.env.consumer
    needs:
      - harmony/automq
      - harmony/redis
    wait: true

  - name: backend
    namespace: harmony
    chart: ../../charts/harmony
    values:
      - values/backend.yaml.gotmpl
    set:
      - name: envFileContent
        file: env/.env.api
    needs:
      - harmony/postgresql
      - harmony/redis
      - harmony/automq
      - harmony/dynamodb-local
    wait: true

  - name: centrifugo
    namespace: harmony
    chart: centrifugal/centrifugo
    values:
      - values/centrifugo.yaml.gotmpl
    needs:
      - harmony/backend
    wait: true

  - name: conduit-cdc
    namespace: harmony
    chart: ../../charts/conduit 
    values:
      - values/conduit.yaml.gotmpl
    set:
      - name: pipelineConfig
        file: config/postgres-cdc.yaml
    needs:
      - harmony/postgresql
      - harmony/automq
    wait: true

  - name: redpanda-connect
    namespace: harmony
    chart: redpanda/connect 
    version: "3.1.0"
    values:
      - values/redpanda-connect.yaml.gotmpl
    set:
      - name: config
        file: config/dynamodb-sink.yaml
    needs:
      - harmony/automq
      - harmony/dynamodb-local
    wait: true

  - name: init-job
    namespace: harmony
    chart: ../../charts/init-job
    values:
      - values/init-job.yaml.gotmpl
    set:
      - name: config.dynamodbTablesJson
        file: config/dynamodb-tables.json
    needs:
      - harmony/dynamodb-local
    wait: true

  - name: kafbat-ui
    namespace: harmony
    chart: kafbat/kafka-ui
    values:
      - values/kafbat-ui.yaml.gotmpl
    needs:
      - harmony/automq
    wait: true