app:
  env: development
  api:
    host: api
    port: 8000
  consumer:
    name: "Harmony CDC Worker Local"

infra:
  aws:
    region: us-east-1
    access_key_id: test
    secret_access_key: test
    
  postgres:
    host: postgres
    port: "5432"
    user: harmony
    password: harmony
    dbname: harmony
    
  redis:
    host: redis
    port: "6379"
    
  dynamodb:
    host: dynamodb
    port: "8000"
    chat_history_table_name: ChatHistory
    
  kafka:
    host: redpanda
    port: "29092"
    
  centrifugo:
    host: centrifugo
    port: "8000"
    api_key: test-cent-api-key
    admin_password: admin
    admin_secret: admin
    allowed_origins: ["*"]
    chat:
      presence_enabled: true
      history_size: 100
      history_ttl: "3600s"

  kafka_connect:
    host: kafka-connect
    port: "8083"