secrets: 
  app:
    secret_key: 64d54ec76be75e906e03e3fba806e2c1ff5f8da12dfb9226e7eea2a72e477c96
  postgres:
    password: harmony_password
  aws:
    access_key_id: test1234
    secret_access_key: test1234
  s3:
    access_key: minioadmin
    secret_key: minioadmin
  centrifugo:
    api_key: test-cent-api-key
    admin_password: admin
    admin_secret: admin