/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  CentrifugoConnectRequest,
  CentrifugoSubscribeRequest,
  HTTPValidationError,
} from ".././model";

import { inject } from "../../utils/injection";

/**
 * @summary Subscribe Proxy
 */
export type subscribeProxyApiV1WsSubscribePostResponse200 = {
  data: unknown;
  status: 200;
};

export type subscribeProxyApiV1WsSubscribePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type subscribeProxyApiV1WsSubscribePostResponseSuccess =
  subscribeProxyApiV1WsSubscribePostResponse200 & {
    headers: Headers;
  };
export type subscribeProxyApiV1WsSubscribePostResponseError =
  subscribeProxyApiV1WsSubscribePostResponse422 & {
    headers: Headers;
  };

export type subscribeProxyApiV1WsSubscribePostResponse =
  | subscribeProxyApiV1WsSubscribePostResponseSuccess
  | subscribeProxyApiV1WsSubscribePostResponseError;

export const getSubscribeProxyApiV1WsSubscribePostUrl = () => {
  return `/api/v1/ws/subscribe`;
};

export const subscribeProxyApiV1WsSubscribePost = async (
  centrifugoSubscribeRequest: CentrifugoSubscribeRequest,
  options?: RequestInit,
): Promise<subscribeProxyApiV1WsSubscribePostResponse> => {
  return inject<subscribeProxyApiV1WsSubscribePostResponse>(
    getSubscribeProxyApiV1WsSubscribePostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(centrifugoSubscribeRequest),
    },
  );
};

/**
 * @summary Connect Proxy
 */
export type connectProxyApiV1WsConnectPostResponse200 = {
  data: unknown;
  status: 200;
};

export type connectProxyApiV1WsConnectPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type connectProxyApiV1WsConnectPostResponseSuccess =
  connectProxyApiV1WsConnectPostResponse200 & {
    headers: Headers;
  };
export type connectProxyApiV1WsConnectPostResponseError =
  connectProxyApiV1WsConnectPostResponse422 & {
    headers: Headers;
  };

export type connectProxyApiV1WsConnectPostResponse =
  | connectProxyApiV1WsConnectPostResponseSuccess
  | connectProxyApiV1WsConnectPostResponseError;

export const getConnectProxyApiV1WsConnectPostUrl = () => {
  return `/api/v1/ws/connect`;
};

export const connectProxyApiV1WsConnectPost = async (
  centrifugoConnectRequest: CentrifugoConnectRequest,
  options?: RequestInit,
): Promise<connectProxyApiV1WsConnectPostResponse> => {
  return inject<connectProxyApiV1WsConnectPostResponse>(
    getConnectProxyApiV1WsConnectPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(centrifugoConnectRequest),
    },
  );
};
