secrets:
    app:
        secret_key: ENC[AES256_GCM,data:pNiJ5shUQELP99kU6xXjzv4w6mvj2QrGOiW9BA7KMqlpAJM44IROl0TNsomyCioKqBLFfp1drPe/agFX/eshNA==,iv:zltg9yzw0Ztq/BSkeebWfaMhC2k0Qv6dBuCSU0RlEg4=,tag:dIIGxDI6K/slbqlrG6V9qA==,type:str]
    postgres:
        password: ENC[AES256_GCM,data:wAckjC1NCvg+f7aR/RxMLSElOFxezWqr,iv:fvBfhLY5Suhg575lRWCK0RR5GWCt2Ni3fKri/rrqNtA=,tag:qWHNzxTj+Myi4+JuOxUBTA==,type:str]
    aws:
        access_key_id: ENC[AES256_GCM,data:uA9i8QxGOyBXRvTM2O8XKSZ/Jns=,iv:tldPoD7HS7Y+MiLxjdbcesWfn/1LrIKfSYydGp0nnNE=,tag:aRXYuCbOV5PzvfUmlUUOzQ==,type:str]
        secret_access_key: ENC[AES256_GCM,data:vTmGATpU+I8EVd83gIM+aSuO+etbBhGxbDnvKWZhVRr/dM08u31wHA==,iv:5UAPwZizqQmw7cdRjd3MCqlFrFsyQoDIMywEuCUx1D8=,tag:MJgr+t+7qKnr1fZ53wTh4w==,type:str]
    s3:
        access_key: ENC[AES256_GCM,data:mghwD99kOqALetnF4dAAD8CoKVE=,iv:3JJIEtDsUgJoYL1BSZie5KctyNeLfzkWRVpIv4rFTNg=,tag:jPdd8Vb0Kw0qYJZiZwHpOw==,type:str]
        secret_key: ENC[AES256_GCM,data:RvurndEjuMiFg1gjdauDOKtMU9pW1TdBfKj36OMASj/34ZBiPkQ2Cw==,iv:ykt8bXYrbeMQp3+YSc7Z4LuYJbAwt4Ei/QBNZdV8Qu0=,tag:LRgWmoE/FOcor7qQg1EDDQ==,type:str]
    centrifugo:
        api_key: ENC[AES256_GCM,data:e2WMqH0F6W8Eal8K4fdmqire8wmRRkvcG4hOkdJYxx4=,iv:EmjObvlvoTxpDublNe4vsId86kPKW4wenRd+MlnBENE=,tag:oaejoZU5EOfQ97IPn6RH4A==,type:str]
        admin_password: ENC[AES256_GCM,data:PNdhNoHu56jH9+/hrdO18w==,iv:1F015G7sYyrvnjd/h/DlwPfbHhovt4qIHlW7yyF/b9w=,tag:Xj6APzLSb1ZgJP6iWeTXCw==,type:str]
        admin_secret: ENC[AES256_GCM,data:zuuz436VclUvmZrgcBtEcQflFynEg7nnEuLfW2WrIx8=,iv:u6U8pGgEfLqHN8XUR3SBCkwmZLQ7PE1upEAdfQRQHqg=,tag:npyZOcWkTfKYAUUDOD14LQ==,type:str]
sops:
    age:
        - recipient: age14v7sn2jseh9g29uchreyn5gxlm0fy3qasdwvghwrq6ae4qsdv9hsk0p3yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeHVtTnRaWWxHMk5wVnBR
            b3U3c3ZzOFhhMzM2OGdWallYRjZNTHhiMEZvClJET0N5OC9tb1VuNzNiR3FuK2h2
            UjJuM3FwbUhZYTkrbG12N0JnS2c0VzQKLS0tIDNBVU1mVmpYQnk1bStxSXBpVUFL
            NXZld1FGSlFmTy9hbHgrNGNkTUNsZXMKtEPvjoKjOUQWh51h0vUDhKm90DwF9msf
            sWUqttUgz5x0qTmX28eGGAHfk/Yqv9q8vppv3CSuBVUzs/x/jlwYoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:26:05Z"
    mac: ENC[AES256_GCM,data:jEWmE2+bFnPovRHwdbM7HdhQ/+AqysA7coiGrmmGL9ET7+2Jz55N11w7UKHBYzR/fzIkR50evTc0CVC0diZ+d9OnV91bZhXw05CykF2FZGIXHSl6NsnYXH99Kk0LNOBTwXkpkNIo10yXHfZpeNZ0AdynW7WGQGZ6OaKTVbT3GfI=,iv:3Ghw5pxviDcxLFhpwMQ4TB+lmM4t2dDTITezNzfI8fQ=,tag:ZQ+M2Po0y0unj9Wtnd9m9g==,type:str]
    encrypted_regex: ^(secrets)$
    version: 3.12.2
