# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "harmony-chat-tf-state"
    dynamodb_table = "harmony-chat-tf-locks"
    encrypt        = true
    key            = "environments/staging/terraform.tfstate"
    region         = "us-east-1"
  }
}
