/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetUserDetailsByEmailApiV1UsersLookupGetParams,
  HTTPValidationError,
  UserChatsResponse,
  UserCreateRequest,
  UserResponse,
} from ".././model";

import { inject } from "../../utils/injection";

/**
 * Registers a new user in the system.

- **Validation**: Checks if the email is unique.
- **Security**: The password is securely hashed (Argon2) before storage.
- **Output**: Returns the generated User ID (ULID).
 * @summary Register a new user
 */
export type signUpApiV1UsersPostResponse201 = {
  data: UserResponse;
  status: 201;
};

export type signUpApiV1UsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type signUpApiV1UsersPostResponseSuccess =
  signUpApiV1UsersPostResponse201 & {
    headers: Headers;
  };
export type signUpApiV1UsersPostResponseError =
  signUpApiV1UsersPostResponse422 & {
    headers: Headers;
  };

export type signUpApiV1UsersPostResponse =
  | signUpApiV1UsersPostResponseSuccess
  | signUpApiV1UsersPostResponseError;

export const getSignUpApiV1UsersPostUrl = () => {
  return `/api/v1/users/`;
};

export const signUpApiV1UsersPost = async (
  userCreateRequest: UserCreateRequest,
  options?: RequestInit,
): Promise<signUpApiV1UsersPostResponse> => {
  return inject<signUpApiV1UsersPostResponse>(getSignUpApiV1UsersPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userCreateRequest),
  });
};

/**
 * Retrieves a list of Chat IDs that the currently logged-in user participates in.
 * @summary Get my chats
 */
export type getMyChatsApiV1UsersMeChatsGetResponse200 = {
  data: UserChatsResponse;
  status: 200;
};

export type getMyChatsApiV1UsersMeChatsGetResponse401 = {
  data: void;
  status: 401;
};

export type getMyChatsApiV1UsersMeChatsGetResponseSuccess =
  getMyChatsApiV1UsersMeChatsGetResponse200 & {
    headers: Headers;
  };
export type getMyChatsApiV1UsersMeChatsGetResponseError =
  getMyChatsApiV1UsersMeChatsGetResponse401 & {
    headers: Headers;
  };

export type getMyChatsApiV1UsersMeChatsGetResponse =
  | getMyChatsApiV1UsersMeChatsGetResponseSuccess
  | getMyChatsApiV1UsersMeChatsGetResponseError;

export const getGetMyChatsApiV1UsersMeChatsGetUrl = () => {
  return `/api/v1/users/me/chats`;
};

export const getMyChatsApiV1UsersMeChatsGet = async (
  options?: RequestInit,
): Promise<getMyChatsApiV1UsersMeChatsGetResponse> => {
  return inject<getMyChatsApiV1UsersMeChatsGetResponse>(
    getGetMyChatsApiV1UsersMeChatsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Retrieves the details of the currently logged-in user.
 * @summary Get current user details
 */
export type getCurrentUserDetailsApiV1UsersMeGetResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getCurrentUserDetailsApiV1UsersMeGetResponse401 = {
  data: void;
  status: 401;
};

export type getCurrentUserDetailsApiV1UsersMeGetResponseSuccess =
  getCurrentUserDetailsApiV1UsersMeGetResponse200 & {
    headers: Headers;
  };
export type getCurrentUserDetailsApiV1UsersMeGetResponseError =
  getCurrentUserDetailsApiV1UsersMeGetResponse401 & {
    headers: Headers;
  };

export type getCurrentUserDetailsApiV1UsersMeGetResponse =
  | getCurrentUserDetailsApiV1UsersMeGetResponseSuccess
  | getCurrentUserDetailsApiV1UsersMeGetResponseError;

export const getGetCurrentUserDetailsApiV1UsersMeGetUrl = () => {
  return `/api/v1/users/me`;
};

export const getCurrentUserDetailsApiV1UsersMeGet = async (
  options?: RequestInit,
): Promise<getCurrentUserDetailsApiV1UsersMeGetResponse> => {
  return inject<getCurrentUserDetailsApiV1UsersMeGetResponse>(
    getGetCurrentUserDetailsApiV1UsersMeGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * **Soft delete** the current user.

- Marks the user as 'tombstoned' in the database.
- The user will no longer be able to log in.
- Historical data (messages) is preserved for data integrity.
 * @summary Deactivate my account
 */
export type deleteMeApiV1UsersMeDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteMeApiV1UsersMeDeleteResponse401 = {
  data: void;
  status: 401;
};

export type deleteMeApiV1UsersMeDeleteResponseSuccess =
  deleteMeApiV1UsersMeDeleteResponse204 & {
    headers: Headers;
  };
export type deleteMeApiV1UsersMeDeleteResponseError =
  deleteMeApiV1UsersMeDeleteResponse401 & {
    headers: Headers;
  };

export type deleteMeApiV1UsersMeDeleteResponse =
  | deleteMeApiV1UsersMeDeleteResponseSuccess
  | deleteMeApiV1UsersMeDeleteResponseError;

export const getDeleteMeApiV1UsersMeDeleteUrl = () => {
  return `/api/v1/users/me`;
};

export const deleteMeApiV1UsersMeDelete = async (
  options?: RequestInit,
): Promise<deleteMeApiV1UsersMeDeleteResponse> => {
  return inject<deleteMeApiV1UsersMeDeleteResponse>(
    getDeleteMeApiV1UsersMeDeleteUrl(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Retrieves the details of a specific user given their email.
 * @summary Get a users details by email
 */
export type getUserDetailsByEmailApiV1UsersLookupGetResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getUserDetailsByEmailApiV1UsersLookupGetResponse404 = {
  data: void;
  status: 404;
};

export type getUserDetailsByEmailApiV1UsersLookupGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserDetailsByEmailApiV1UsersLookupGetResponseSuccess =
  getUserDetailsByEmailApiV1UsersLookupGetResponse200 & {
    headers: Headers;
  };
export type getUserDetailsByEmailApiV1UsersLookupGetResponseError = (
  | getUserDetailsByEmailApiV1UsersLookupGetResponse404
  | getUserDetailsByEmailApiV1UsersLookupGetResponse422
) & {
  headers: Headers;
};

export type getUserDetailsByEmailApiV1UsersLookupGetResponse =
  | getUserDetailsByEmailApiV1UsersLookupGetResponseSuccess
  | getUserDetailsByEmailApiV1UsersLookupGetResponseError;

export const getGetUserDetailsByEmailApiV1UsersLookupGetUrl = (
  params: GetUserDetailsByEmailApiV1UsersLookupGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/users/lookup?${stringifiedParams}`
    : `/api/v1/users/lookup`;
};

export const getUserDetailsByEmailApiV1UsersLookupGet = async (
  params: GetUserDetailsByEmailApiV1UsersLookupGetParams,
  options?: RequestInit,
): Promise<getUserDetailsByEmailApiV1UsersLookupGetResponse> => {
  return inject<getUserDetailsByEmailApiV1UsersLookupGetResponse>(
    getGetUserDetailsByEmailApiV1UsersLookupGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Retrieves the details of a specific user given their ID.
 * @summary Get a users details by ID
 */
export type getUserDetailsByIdApiV1UsersUserIdGetResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getUserDetailsByIdApiV1UsersUserIdGetResponse404 = {
  data: void;
  status: 404;
};

export type getUserDetailsByIdApiV1UsersUserIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserDetailsByIdApiV1UsersUserIdGetResponseSuccess =
  getUserDetailsByIdApiV1UsersUserIdGetResponse200 & {
    headers: Headers;
  };
export type getUserDetailsByIdApiV1UsersUserIdGetResponseError = (
  | getUserDetailsByIdApiV1UsersUserIdGetResponse404
  | getUserDetailsByIdApiV1UsersUserIdGetResponse422
) & {
  headers: Headers;
};

export type getUserDetailsByIdApiV1UsersUserIdGetResponse =
  | getUserDetailsByIdApiV1UsersUserIdGetResponseSuccess
  | getUserDetailsByIdApiV1UsersUserIdGetResponseError;

export const getGetUserDetailsByIdApiV1UsersUserIdGetUrl = (userId: string) => {
  return `/api/v1/users/${userId}`;
};

export const getUserDetailsByIdApiV1UsersUserIdGet = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserDetailsByIdApiV1UsersUserIdGetResponse> => {
  return inject<getUserDetailsByIdApiV1UsersUserIdGetResponse>(
    getGetUserDetailsByIdApiV1UsersUserIdGetUrl(userId),
    {
      ...options,
      method: "GET",
    },
  );
};
