image:
  dynamodbInit: init-dynamodb:local
  curl: curlimages/curl:latest
  pullPolicy: Never

dynamodb:
  endpoint: "http://dynamodb-local:8000"
  region: "us-east-1"

config:
  dynamodbTablesJson: ""