image:
  dynamodbInit:
    repository: "init-dynamodb"
    tag: "local"
    pullPolicy: "Never"
  curl: curlimages/curl:latest

dynamodb:
  endpoint: "http://dynamodb-local:8000"
  region: "us-east-1"

config:
  dynamodbTablesJson: ""