{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: app-auth-secret
  type: Opaque
stringData:
  secret_key: {{ .Values.secrets.app.secret_key | quote }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: app-auth-secret-es
  spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.infra.secrets.manager_name }}
        property: app.secret_key
{{- end }}