{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: app-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secret_key: {{ .Values.secrets.app.secret_key | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-auth-secret-es
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: harmony/{{ .Values.environment }}/secrets
        property: app.secret_key
{{- end }}