{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: aws-auth-secret
  type: Opaque
stringData:
  access_key_id: {{ .Values.secrets.aws.access_key_id | quote }}
  secret_access_key: {{ .Values.secrets.aws.secret_access_key | quote }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: aws-auth-secret-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: aws-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: access_key_id
      remoteRef:
        key: {{ .Values.infra.secrets.manager_name }}
        property: aws.access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: {{ .Values.infra.secrets.manager_name }}
        property: aws.secret_access_key
{{- end }}