{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: centrifugo-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ .Values.secrets.centrifugo.api_key | quote }}
  admin_password: {{ .Values.secrets.centrifugo.admin_password | quote }}
  admin_secret: {{ .Values.secrets.centrifugo.admin_secret | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: centrifugo-auth-secret-es
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: centrifugo-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: harmony/{{ .Values.environment }}/secrets
        property: centrifugo.api_key
    - secretKey: admin_password
      remoteRef:
        key: harmony/{{ .Values.environment }}/secrets
        property: centrifugo.admin_password
    - secretKey: admin_secret
      remoteRef:
        key: harmony/{{ .Values.environment }}/secrets
        property: centrifugo.admin_secret
{{- end }}