apiVersion: v1
kind: Secret
metadata:
  name: centrifugo-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ .Values.secrets.centrifugo.api_key | quote }}
  admin_password: {{ .Values.secrets.centrifugo.admin_password | quote }}
  admin_secret: {{ .Values.secrets.centrifugo.admin_secret | quote }}