{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-auth-secret
type: Opaque
stringData:
  postgres_password: {{ .Values.secrets.postgres.password | quote }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: postgres-auth-secret-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres_password
      remoteRef:
        key: {{ .Values.infra.secrets.manager_name }}
        property: postgres.password
{{- end }}