apiVersion: v1
kind: Secret
metadata:
  name: s3-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access_key: {{ .Values.secrets.s3.access_key | quote }}
  secret_key: {{ .Values.secrets.s3.secret_key | quote }}