{{- if ne .Values.environment "local" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.infra.aws.region | default "us-east-1" }}
{{- end }}