{{- if ne .Values.environment "local" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  namespace: {{ .Release.Namespace }}
  name: aws-parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.infra.aws.region | default "us-east-1" }}
{{- end }}