{{- if ne .Values.environment "local" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-outputs-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: tf-outputs-secret
    creationPolicy: Owner
  data:
    - secretKey: rds_endpoint
      remoteRef:
        key: /harmony/{{ .Values.environment }}/rds_endpoint
    - secretKey: redis_endpoint
      remoteRef:
        key: /harmony/{{ .Values.environment }}/redis_endpoint
{{- end }}