name: Monorepo Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set lower case owner name
        run: |
          echo "ORG=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/harmony-backend:${{ github.ref_name }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/harmony-frontend:${{ github.ref_name }}
          
  create-github-release:
    needs: build-and-publish-images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
